; 10進数、16進数（0x付加）のどちらでも定義可能
; *付きでポインタ参照にすることも可能
; $付きでバイト列検索し、その直後をポインタ参照可能
; バイト列の後に、「, 数字」を記述すると、その分後ろにズレる
; [BEGIN][XXXX] - [END][XXXX]で囲んで、複数設定可能

[BEGIN][DEFAULT]
; CFRU有無
IsAppliedCFRU = false

; 空き領域検索
FreeSpaceFinderAddress = 0x00700000
FreeSpaceByteAmount = 2048

; ポケモン名
PokemonNameTableAddress = *0x00000144
PokemonNameEntryLength = 0x6
PokemonNameCount = 412
; ポケモン画像
PokemonSpriteFrontImageTableAddress = *0x00000128
PokemonSpriteBackImageTableAddress  = *0x0000012C
PokemonSpriteNormalPaletteTableAddress  = *0x00000130
PokemonSpriteShinyPaletteTableAddress  = *0x00000134
PokemonSpriteCount = 440
; ポケモンアイコン
PokemonIconImageTableAddress = *0x00000138
PokemonIconPaletteIndexTableAddress = *0x0000013C
PokemonIconCount = 440
PokemonIconPaletteAddressTableAddress = *0x00000140
PokemonIconPaletteAddressCount = 3
; ポケモン足跡
PokemonFootprintTableAddress = *0x001069B0
PokemonFootprintCount = 412
NoFootprintStartIndex = 0x19C
; ポケモン表示位置　バトル時
PokemonCoordinateBattleAllyTableAddress = *0x00073DD8
PokemonCoordinateBattleEnemyTableAddress = *0x0001179C
PokemonCoordinateBattleCount = 440
PokemonCoordinateBattleEnemyShadowTableAddress = *0x00034E6C
PokemonCoordinateBattleEnemyShadowCount = 412
; ポケモン表示位置　アイテム使用時
PokemonCoordinateItemUseTableAddress = *0x0012F2E8
PokemonCoordinateItemUseCount = 413
PokemonCoordinateItemUseStartIndex = 0x1




; アイテム
ItemDataTableAddress = *0x000001C8
ItemDataEntryLength = 0x28
ItemDataCount = 375
ItemNameEntryLength = 0xA
ItemNameMaxLength = 0x9
ItemSpriteTableAddress = *0x000981FC
ItemEffectTableAddress = *0x00039A1C
ItemEffectFirstIndex = 0xD
ItemEffectLastIndex = 0xAF

; トレーナー肩書き
TrainerClassNameTableAddress = *0x000D90AC
TrainerClassNameEntryLength = 0xB
TrainerClassNameCount = 107
; トレーナー賞金
TrainerClassPrizeMultiplierTableAddress = *0x000251B8
TrainerClassPrizeMultiplierCount = 105
;; 要CFRU
EnableTrainerClassEncounterMusic = false
TrainerClassEncounterMusicTableAddress = $A1FC10BD094B0A4801F09CFCE4E7C046, 0x14
EnableTrainerClassBattleMusic = false
TrainerClassBattleMusicTableAddress = $4000405B002800D072E7236899E7C046, 0x24
EnableTrainerClassPokeBall = false
TrainerClassPokeBallTableAddress = $3433E854042C00D10EE14346DB69E9E7, 0x24
EnableTrainerClassBaseIV = false
TrainerClassBaseIVTableAddress = $3433E854042C00D10EE14346DB69E9E7, 0x10

; トレーナー画像
TrainerSpriteImageTableAddress = *0x00033EB0
TrainerSpritePaletteTableAddress = *0x00033EC0
TrainerSpriteYOffsetTableAddress = *0x000375E8
TrainerSpriteAnimationPointerTableAddress = *0x0003F060
TrainerSpriteCount = 148

[END][DEFAULT]
