; 10進数、16進数（0x付加）のどちらでも定義可能
; *付きでポインタ参照にすることも可能
; $付きでバイト列検索し、その直後をポインタ参照可能
; バイト列の後に、「, 数字」を記述すると、その分後ろにズレる
; [BEGIN][XXXX] - [END][XXXX]で囲んで、複数設定可能

[BEGIN][DEFAULT]
; CFRU有無
IsAppliedCFRU = false

; 空き領域検索
FreeSpaceFinderAddress = 0x00700000
FreeSpaceByteAmount = 2048

; ポケモン名
PokemonNameTableAddress = *0x00000144
PokemonNameEntryLength = 0x6
PokemonNameCount = 412

; ポケモン画像
PokemonSpriteFrontImageTableAddress = *0x00000128
PokemonSpriteBackImageTableAddress  = *0x0000012C
PokemonSpriteNormalPaletteTableAddress  = *0x00000130
PokemonSpriteShinyPaletteTableAddress  = *0x00000134
PokemonSpriteCount = 440
; アイコン
PokemonIconImageTableAddress = *0x00000138
PokemonIconPaletteIndexTableAddress = *0x0000013C
PokemonIconCount = 440
PokemonIconPaletteAddressTableAddress = *0x00000140
PokemonIconPaletteAddressCount = 3
; 足跡
PokemonFootprintTableAddress = *0x001069B0
PokemonFootprintCount = 412
NoFootprintStartIndex = 0x19C

; 表示位置　バトル時
PokemonCoordinateBattleAllyTableAddress = *0x00073DD8
PokemonCoordinateBattleEnemyTableAddress = *0x0001179C
PokemonCoordinateBattleCount = 440
PokemonCoordinateBattleEnemyShadowTableAddress = *0x00034E6C
PokemonCoordinateBattleEnemyShadowCount = 412
; 表示位置　アイテム使用時
PokemonCoordinateItemUseTableAddress = *0x0012F2E8
PokemonCoordinateItemUseCount = 413
PokemonCoordinateItemUseStartIndex = 0x1

; ポケモン基本情報
PokemonStatsTableAddress = *0x000001BC
PokemonStatsCount = 412
;; 要CFRU
EnableStatsExpansion = false
; 特性
AbilityNameTableAddress = *0x000001C0
AbilityNameEntryLength = 0x8
AbilityNameCount = 78
; タイプ
TypeNameTableAddress = *0x000D9564
TypeNameEntryLength = 0x5
TypeNameCount = 18

; 進化
PokemonEvolutionTableAddress = *0x0004265C
PokemonEvolutionEntryCount = 412
PokemonEvolutionSlotLength = 0x8
PokemonEvolutionSlotCount = 5

; レベル技
PokemonLearnsetTableAddress= *0x0003E1E8
PokemonLearnsetEntryCount = 412
;; 要CFRU
EnableLearnsetExpansion = false

; 図鑑情報
PokedexTableAddress = *0x00088A10
PokedexCount = 387
PokedexCategoryEntryLength = 0x6
PokedexCategoryMaxLength = 0x5

; 鳴き声
CryData1TableAddress = *0x000718B8
CryData2TableAddress = *0x000718A8
CryDataCount = 388
NoCryDataStartIndex = 0xFC
NoCryDataEndIndex = 0x114
ExtendCryTableAddress= *0x00042A18
ExtendCryCount = 135
ExtendCryFirstIndex = 0x115
;; 要CFRU
EnableIndexedCryDataTable = false

; ポケモン戦闘BGM
;; 要CFRU
EnablePokemonBattleMusic = false
PokemonBattleMusicTableAddress = $4000405B002800D072E7236899E7C046, 0xC
PokemonBattleMusicCount = 412

; 図鑑番号
PokedexOrderTableAddress = *0x0004292C
PokedexOrderCount = 411
PokedexDisplayCount = 386

; 図鑑生息地
PokedexHabitatTableAddress = *0x001073E0

; 図鑑索引
PokedexSearchSortAiueoTableAddress = *0x00104448
PokedexSearchSortAiueoCount = 411
PokedexSearchSortTypeTableAddress = *0x001044EC
PokedexSearchSortTypeCount = 411
PokedexSearchSortWeightTableAddress = *0x00104584
PokedexSearchSortWeightCount = 386
PokedexSearchSortHeightTableAddress = *0x00104620
PokedexSearchSortHeightCount = 386
;; 要CFRU
EnableSpeciesIndexed = false

; 技名
MoveNameTableAddress = *0x00000148
MoveNameEntryLength = 0x8
MoveNameCount = 355
; 技マシン
TmHmListTableAddress = *0x001263D8
TmHmLearnTableAddress = *0x000432B4
TmHmTutorEntryLength = 2
TmHmCount = 58
TmCount = 50
HmCount = 8
; 教え技
TutorListTableAddress = *0x001213D4
TutorLearnTableAddress = *0x00121420
TutorCount = 15

; タマゴ技
EggMoveTableAddress = *0x00045214
EnableEggMoveSizeCalc = true
EggMoveTableSizeAddress = 0x00045288

; アイテム
ItemDataTableAddress = *0x000001C8
ItemDataEntryLength = 0x28
ItemDataCount = 375
ItemNameEntryLength = 0xA
ItemNameMaxLength = 0x9
ItemSpriteTableAddress = *0x000981FC
ItemEffectTableAddress = *0x00039A1C
ItemEffectFirstIndex = 0xD
ItemEffectLastIndex = 0xAF

; トレーナー肩書き
TrainerClassNameTableAddress = *0x000D90AC
TrainerClassNameEntryLength = 0xB
TrainerClassNameCount = 107
; トレーナー賞金
TrainerClassPrizeMultiplierTableAddress = *0x000251B8
TrainerClassPrizeMultiplierCount = 105
;; 要CFRU
EnableTrainerClassEncounterMusic = false
TrainerClassEncounterMusicTableAddress = $A1FC10BD094B0A4801F09CFCE4E7C046, 0x14
EnableTrainerClassBattleMusic = false
TrainerClassBattleMusicTableAddress = $4000405B002800D072E7236899E7C046, 0x24
EnableTrainerClassPokeBall = false
TrainerClassPokeBallTableAddress = $3433E854042C00D10EE14346DB69E9E7, 0x24
EnableTrainerClassBaseIV = false
TrainerClassBaseIVTableAddress = $3433E854042C00D10EE14346DB69E9E7, 0x10

; トレーナー画像
TrainerSpriteImageTableAddress = *0x00033EB0
TrainerSpritePaletteTableAddress = *0x00033EC0
TrainerSpriteYOffsetTableAddress = *0x000375E8
TrainerSpriteAnimationPointerTableAddress = *0x0003F060
TrainerSpriteCount = 148

; トレーナーリスト
TrainerListTableAddress = *0x0000F5C0
TrainerListEntryLength = 0x20
TrainerListEntryCount = 743
TrainerNameEntryLength = 0x6

[END][DEFAULT]


[BEGIN][DPE+CFRU]

; CFRU有無
IsAppliedCFRU = true

; 空き領域検索
FreeSpaceFinderAddress = 0x00700000
FreeSpaceByteAmount = 2048

; ポケモン名
PokemonNameTableAddress = *0x00000144
PokemonNameEntryLength = 0x8
PokemonNameCount = 1440

; ポケモン画像
PokemonSpriteFrontImageTableAddress = *0x00000128
PokemonSpriteBackImageTableAddress  = *0x0000012C
PokemonSpriteNormalPaletteTableAddress  = *0x00000130
PokemonSpriteShinyPaletteTableAddress  = *0x00000134
PokemonSpriteCount = 1440
; アイコン
PokemonIconImageTableAddress = *0x00000138
PokemonIconPaletteIndexTableAddress = *0x0000013C
PokemonIconCount = 1440
PokemonIconPaletteAddressTableAddress = *0x00000140
PokemonIconPaletteAddressCount = 3
; 足跡
PokemonFootprintTableAddress = *0x001069B0
PokemonFootprintCount = 412
NoFootprintStartIndex = 0x0

; 表示位置　バトル時
PokemonCoordinateBattleAllyTableAddress = *0x00073DD8
PokemonCoordinateBattleEnemyTableAddress = *0x0001179C
PokemonCoordinateBattleCount = 1440
PokemonCoordinateBattleEnemyShadowTableAddress = *0x00034E6C
PokemonCoordinateBattleEnemyShadowCount = 1440
; 表示位置　アイテム使用時
PokemonCoordinateItemUseTableAddress = *0x0012F2E8
PokemonCoordinateItemUseCount = 1440
PokemonCoordinateItemUseStartIndex = 0x0

; ポケモン基本情報
PokemonStatsTableAddress = *0x000001BC
PokemonStatsCount = 1440
;; 要CFRU
EnableStatsExpansion = true
; 特性
AbilityNameTableAddress = *0x000001C0
AbilityNameEntryLength = 0x11
AbilityNameCount = 311
; タイプ
TypeNameTableAddress = *0x000D9564
TypeNameEntryLength = 0x6
TypeNameCount = 24

; 進化
PokemonEvolutionTableAddress = *0x0004265C
PokemonEvolutionEntryCount = 1440
PokemonEvolutionSlotLength = 0x8
PokemonEvolutionSlotCount = 16

; レベル技
PokemonLearnsetTableAddress= *0x0003E1E8
PokemonLearnsetEntryCount = 1440
;; 要CFRU
EnableLearnsetExpansion = true

; 図鑑情報
PokedexTableAddress = *0x00088A10
PokedexCount = 1026
PokedexCategoryEntryLength = 0x6
PokedexCategoryMaxLength = 0x6

; 鳴き声
CryData1TableAddress = *0x000718B8
CryData2TableAddress = *0x000718A8
CryDataCount = 1440
NoCryDataStartIndex = 0xFC
NoCryDataEndIndex = 0x114
ExtendCryTableAddress= *0x00042A18
ExtendCryCount = 135
ExtendCryFirstIndex = 0x115
;; 要CFRU
EnableIndexedCryDataTable = true

; ポケモン戦闘BGM
;; 要CFRU
EnablePokemonBattleMusic = true
PokemonBattleMusicTableAddress= $4000405B002800D072E7236899E7C046, 0xC
PokemonBattleMusicCount= 412

; 図鑑番号
PokedexOrderTableAddress = *0x0004292C
PokedexOrderCount = 1439
PokedexDisplayCount = 1025

; 図鑑生息地
PokedexHabitatTableAddress = *0x001073E0

; 図鑑索引
PokedexSearchSortAiueoTableAddress = *0x00104448
PokedexSearchSortAiueoCount = 1021
PokedexSearchSortTypeTableAddress = *0x001044EC
PokedexSearchSortTypeCount = 1034
PokedexSearchSortWeightTableAddress = *0x00104584
PokedexSearchSortWeightCount = 1015
PokedexSearchSortHeightTableAddress = *0x00104620
PokedexSearchSortHeightCount = 1018
;; 要CFRU
EnableSpeciesIndexed = true

; 技名
MoveNameTableAddress = *0x00000148
MoveNameEntryLength = 0x10
MoveNameCount = 992
; 技マシン
TmHmListTableAddress = *0x001263D8
TmHmLearnTableAddress = *0x000432B4
TmHmTutorEntryLength = 2
TmHmCount = 128
TmCount = 120
HmCount = 8
; 教え技
TutorListTableAddress = *0x001213D4
TutorLearnTableAddress = *0x00121420
TutorCount = 152

; タマゴ技
EggMoveTableAddress = *0x00045214
EnableEggMoveSizeCalc = false
EggMoveTableSizeAddress = 0x00045288

; アイテム
ItemDataTableAddress = *0x000001C8
ItemDataEntryLength = 0x28
ItemDataCount = 774
ItemNameEntryLength = 0xA
ItemNameMaxLength = 0x9
ItemSpriteTableAddress = *0x000981FC
ItemEffectTableAddress = *0x00039A1C
ItemEffectFirstIndex = 0x0
ItemEffectLastIndex = 0x773

; トレーナー肩書き
TrainerClassNameTableAddress = *0x000D90AC
TrainerClassNameEntryLength = 0xB
TrainerClassNameCount = 107
; トレーナー賞金
TrainerClassPrizeMultiplierTableAddress = *0x000251B8
TrainerClassPrizeMultiplierCount = 105
;; 要CFRU
EnableTrainerClassEncounterMusic = false
TrainerClassEncounterMusicTableAddress = $A1FC10BD094B0A4801F09CFCE4E7C046, 0x14
EnableTrainerClassBattleMusic = true
TrainerClassBattleMusicTableAddress = $4000405B002800D072E7236899E7C046, 0x24
EnableTrainerClassPokeBall = true
TrainerClassPokeBallTableAddress = $3433E854042C00D10EE14346DB69E9E7, 0x24
EnableTrainerClassBaseIV = true
TrainerClassBaseIVTableAddress = $3433E854042C00D10EE14346DB69E9E7, 0x10

; トレーナー画像
TrainerSpriteImageTableAddress = *0x00033EB0
TrainerSpritePaletteTableAddress = *0x00033EC0
TrainerSpriteYOffsetTableAddress = *0x000375E8
TrainerSpriteAnimationPointerTableAddress = *0x0003F060
TrainerSpriteCount = 148

[END][DPE+CFRU]
